additionalRepositories:
  - url: https://bitbucket.org/legendcorp/codelibrary/src/master/
    # checkoutLocation is optional and relative to /workspaces.
    # by default the location defaults to the repository name.
    checkoutLocation: CodeLibrary

#tasks:
#  - init: cd LOCAL_WORKING/Docker && ./setup.sh
#    command: cd LOCAL_WORKING/Docker && ./start.sh
tasks:
  - before: |
      echo "$SSH_ID_RSA" | base64 --decode >> ~/.ssh/id_rsa
  - init: |
      cd LOCAL_WORKING/Docker && ./setup.sh
  - command: |
      cd LOCAL_WORKING/Docker && ./start.sh
ports:
  - port: 80
    onOpen: open-preview
