additionalRepositories:
  - url: https://bitbucket.org/legendcorp/codelibrary/src/master/
    # checkoutLocation is optional and relative to /workspaces.
    # by default the location defaults to the repository name.
    checkoutLocation: CodeLibrary

tasks:
    - name: Setup
      init: cd LOCAL_WORKING/Docker && ./setup.sh
#    - name: Start
#      command: cd LOCAL_WORKING/Docker && ./start.sh

ports:
  - port: 80
    onOpen: open-preview
