export default {
    "tagRules": {
        '/games/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Slot Reviews'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/reviews/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Reviews'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/deposit/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Banking', 'Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/software/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Software', 'Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/guides/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['Guides'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
    },
    "tagDefaults": {
            'mainCategory': 'No Tag',
            'subCategories': [],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
    "pageTags": {
        '/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Homepage', 'Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/games/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Free Games'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/reviews/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['Reviews'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/deposit/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['Banking'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/software/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['Software'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/guides/faq/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['FAQ'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/privacy': {
            'mainCategory': 'Non-Commercial',
            'subCategories': [''],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/sitemap': {
            'mainCategory': 'Non-Commercial',
            'subCategories': [''],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/responsible-gambling': {
            'mainCategory': 'Non-Commercial',
            'subCategories': [''],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/no-download': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/online-casinos': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/android': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/apps-guide': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/tablets': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/iphone': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/ipad': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/mobile': {
            'mainCategory': 'Commercial',
            'subCategories': ['Devices','Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/real-money': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/free': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['Free Games'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/about/': {
            'mainCategory': 'Non-Commercial',
            'subCategories': ['About Us'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/progressive-jackpots': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/bonuses': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/vip': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'English',
        },
        '/fr/': {
            'mainCategory': 'Commercial',
            'subCategories': ['Toplists'],
            'mainVertical': 'Casino',
            'subVertical': 'Slots',
            'triVertical': '',
            'country': 'Canada',
            'language': 'French',
        },
    },
};