<?php $title = 'Legal Slots Gambling Guide For Canadians In '.date('Y').'';
$desc = 'Canadian Slots Winnings Taxes And Laws '.date('Y').' - Discover what taxes are due on slot machine winnings with our guide. Learn about the legalities of Canadian slots play.';
$bc = 'Legal Slots Gambling Guide For Canadians';

$customATF = 'guide';
include($_SERVER['DOCUMENT_ROOT'] . "/includes/onca_header.php");
?>

<section class="section type-section-padding-bottom">
	<div class="container">
		<h1 class="title title--h2"><img class="artright" src="/images/corner/guide/legal-slots.png" alt="Are Canadians Taxed Gambling" width="200" height="150">A Complete Guide To Slots Gambling Taxes and Legalities for Canadians</h1>
		<p>
			Canadians love to gamble, but with that comes all sorts of questions as to whether or not a player is subjected to paying any tax on their winnings. If you want to “play it straight” and avoid any legal hook-ups, you need to know the tax laws before you play slots, or any other gambling game.
		</p>
		<h2 class="title title--h2">First things first, are Canadians taxed on winnings?</h2>
		<p>
			Canadians pay more taxes than their neighbours to the South, but when it comes to slots, blackjack, poker or gambling in general, you are not required to pay taxes on any cash that you win. This also applies to horse racing, sports betting, lotteries and other games of chance. However, any interest earned on the winnings is taxable and must be reported on a T5 form.
		</p>
		<p>
			The reason casino games are not treated as a taxable source of income is because the winnings are not generated by an office, employment, or property. Furthermore, gambling is not considered by Canadian law to be a business because it relies upon chance and the chance of most players making a living on this is rather small.
		</p>
		<p>
			All that said, when you gamble in Canada (be it online or offline) what you win is what you get.
		</p>
		<h2 class="title title--h2">Gambling across the border</h2>
		<p>
			If you are a Canadian and you travel to the US to gamble, you will be required to pay taxes on any winnings overC$1200 USD. You don’t even get the option to not disclose it, and therefore, not pay it. The casino automatically deducts a whopping 30% whenever you cash out. Anything underC$1200 is not taxed.  However, if you are a Canadian working in the US, under Article XXII of the <a href="https://www.fin.gc.ca/treaties-conventions/usa_-eng.asp" class="text--link" rel="noreferrer" target="_blank">Canada-U.S. Tax Treaty</a>, you can deduct U.S. source gambling losses from your U.S. source gambling winnings, and obtain a casino tax refund based on that amount.
		</p>
		<p>
			If you are an American and gambling in Windsor or any other top Canadian casinos, you will not be taxed by the casino itself. However, you are legally required to tell the IRS about any of your winnings, even if you’ve won them abroad.
		</p>
		<h2 class="title title--h2">What about professional, full-time gambling? </h2>
		<p>
			Canadian law states that if you earn a living as a full time slots player, poker player or any other kind of gambler, you are required to file taxes. This is because as a pro gambler, you are seen as operating your own business, and that qualifies as being taxable.
		</p>
		<p>
			It must be noted that the Canada Revenue Agency <a href="http://www.lawnow.org/are-gambling-winnings-a-prize-under-the-income-tax-act/" class="text--link" rel="noreferrer" target="_blank">has been very reluctant</a> to assess people as having income from being a full time gambler. This is because if their “business” profits are taxable, then their business losses can also be used to reduce income from that business and (in the case of individuals) from other businesses or from employment. If the CRA starts to crack down on these individuals, it could ultimately result in a huge drain on the overall tax revenues in the entire country.
		</p>
		<h2  class="title title--h2"><img class="artright lazy" src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 3'%3E%3C/svg%3E" data-src="/images/corner/guide/taxed-gambling.png" alt="Canadians Taxed Gambling" width="200" height="150">A quick comparison of tax laws across borders</h2>
		<p>
			Canadian gambling tax laws are comparable to those in the UK or Australia. Both countries gambling laws are nearly the same in that any winnings are not taxed. However, casinos are taxed and that income is used for new schools, parks and community facilities.
		</p>
		<h2 class="title title--h2">The Court Says “No Taxes for Financially Successful Sports Bettors”</h2>
		<p>
			A team of sports bettors recently went up against Canadian courts <a href="https://taxinterpretations.com/tax-topics/income-tax-act/section-248/subsection-248-1/business" class="text--link" rel="noreferrer" target="_blank">(2007, D.T.C. 307 (T.C.C.))</a> regarding whether or not they should have to pay taxes.  They were financially successful and placed sports wagers on a full time basis. They had a system down and were very efficient at what they did. The courts concluded that they were compulsive gamblers “continually trying their luck at a game of chance.” The verdict: not guilty, no taxes to be paid.
		</p>
		<h2 class="title title--h2">The Bottom Line – what you need to know</h2>
		<p>
			Gambling, whether online or offline, in Canada is completely legal. In fact, to our knowledge, no one has ever been charged with a crime for indulging in a game of slots. If you are really unsure about playing at a casino, be smart and double check.
		</p>
		<p>
			In regards to paying taxes on your winnings, those are yours unless gambling has become your profession. Again, if you are not sure about paying taxes, consult a tax accountant for advice.
		</p>
		<?php
		bottom_box(false,$script);
		?>
	</div>
</section>

<?php include($_SERVER['DOCUMENT_ROOT'] . "/includes/onca_footer.php");
